### ISSUE TITLE
You could also just activate this feature within InformedDelivery :)

### ISSUE THREAD

**Issue by mariniertje** [kylefrost/todays-mail#1]
Great work, Kyle, and like your solution/approach.

But you do know you can just enable this feature within Informed Delivery, right?

If you go to SETTINGS, you will see the following text with a ON/OFF switch:

> **Mail**
**Turn on my Informed Delivery email notifications.**
An email will be sent to <your_emailadres@example.com> each day that your household receives letter-sized mail that is processed through the United States Postal Service® automation equipment. Notifications are not sent on days when there is no mail to be delivered, if no mail is processed through automation, or on Sundays or federal holidays. If you would like to update your email please visit USPS Profile page.

**Comment by kylejfrost** [comment]
This project was more of a "could I?" project, and not a solution to a problem that hadn't been solved. Plus, this adds more flexibility like being able to customize the email and send it to as many addresses as I want (it goes to both me and my wife). Also, I keep an archive of all the scans for whatever reason.
